
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '0.5'
        reservations:
          memory: 1g
          cpus: '0.25'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app

  db:
    image: nouchka/sqlite3
    volumes:
      - ./server/db:/var/lib/sqlite
    expose:
      - "3306"
